name: flutter_projeto
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3  # Mantenha a versão atual
  bcrypt: ^1.1.3
  cloud_firestore: ^4.15.6
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  firebase_storage: ^11.6.7
  postgres: ^3.1.2
  
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
